blank_issues_enabled: false
contact_links:
  - name: Gateway help or general discussions
    url: https://github.com/infinilabs/gateway/discussions
    about: Please use Discussions as the place to connect with other members of our community, for help and sharing.