blank_issues_enabled: false
contact_links:
  - name: Looking for help or discussion
    url: https://discord.gg/4tKTMkkvVX
    about: Please use Discord as the place to connect with other members of our community, for help and sharing.
