blank_issues_enabled: false
contact_links:
  - name: gateway bug report
    url: https://github.com/infinilabs/gateway/issues/new/choose
    about: Create a bug report over at the gateway repository.