blank_issues_enabled: false
contact_links:
  - name: Looking for help or discussion
    url: https://github.com/infinilabs/gateway/discussions
    about: Please use Discussions as the place to connect with other members of our community, for help and sharing.